language: php

php:
  - "7.1"

services:
  - docker

before_install:
#  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
  - export OPENCART_VERSION=3.0.2.0
  - docker build -t $DOCKER_USER/frontendapp:${OPENCART_VERSION} .
  - docker build -t $DOCKER_USER/frontendapp:${OPENCART_VERSION}-installer -f Dockerfile-installer .
  - docker tag $DOCKER_USER/frontendapp:${OPENCART_VERSION} $DOCKER_USER/frontendapp:latest
  - docker push $DOCKER_USER/frontendapp:${OPENCART_VERSION}
  - docker push $DOCKER_USER/frontendapp:${OPENCART_VERSION}-installer
  - docker push $DOCKER_USER/frontendapp:latest

script:
  - docker --version
  - docker build -t frontendapp .
  - docker images
  
deploy:
  - provider: script
    script: ./build-tools/travispushtoecr.sh master "frontendapp"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./build-tools/travispushtoecr.sh tag "frontendapp"
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+  
