language: php

php:
  - "7.1"

services:
  - docker

before_install:
#  - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
  - docker --version
  - docker build -t frontendapp1 .
  - docker images
  
deploy:
  - provider: script
    script: ./travispushtoecr.sh master "frontendapp1"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./travispushtoecr.sh tag "frontendapp1"
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+  
